site_name: Simulation Software Engineering
site_url: https://simulation-software-engineering.github.io/homepage/
site_author: Alexander Jaust and Benjamin Uekermann
site_description: >-
  TBD

nav:
  - Simulation Software Engineering: index.md
  - Course information: course-information.md
  - Course content: course-content.md
  - Staff/Contact: staff.md

# Point to repository name and set base branch to main
repo_name:  Simulation-Software-Engineering/homepage
repo_url: https://github.com/Simulation-Software-Engineering/homepage
edit_uri: edit/main/docs/

theme:
  name: material
#  icon:
#    logo: Simulation-Software-Engineering/homepage
#    repo: fontawesome/brands/git-alt
#  palette:
#    primary: blue
#    accent: blue
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.tabs

  logo: logo/sse-logo-200x200.png

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ajaust
    - icon: fontawesome/brands/github
      link: https://github.com/uekerman


markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences
